// <auto-generated />
using System;
using ConsoleApp1;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ConsoleApp1.Migrations
{
    [DbContext(typeof(TareasDbContext))]
    partial class TareasDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("ConsoleApp1.Detalles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("fecha")
                        .HasColumnType("TEXT");

                    b.Property<int?>("recursoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("tareasId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("tiempo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("recursoId");

                    b.HasIndex("tareasId");

                    b.ToTable("Detalle");
                });

            modelBuilder.Entity("ConsoleApp1.Recursos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("nombre")
                        .HasColumnType("TEXT");

                    b.Property<int?>("usuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("usuarioId");

                    b.ToTable("Recurso");
                });

            modelBuilder.Entity("ConsoleApp1.Tareas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("estado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("estimacion")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("responsableId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("tipoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("titulo")
                        .HasColumnType("TEXT");

                    b.Property<string>("vencimiento")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("responsableId");

                    b.HasIndex("tipoId");

                    b.ToTable("Tarea");
                });

            modelBuilder.Entity("ConsoleApp1.TipoTarea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TipoTarea");
                });

            modelBuilder.Entity("ConsoleApp1.Usuarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("clave")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("nombre")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("ConsoleApp1.Detalles", b =>
                {
                    b.HasOne("ConsoleApp1.Recursos", "recurso")
                        .WithMany()
                        .HasForeignKey("recursoId");

                    b.HasOne("ConsoleApp1.Tareas", "tareas")
                        .WithMany()
                        .HasForeignKey("tareasId");
                });

            modelBuilder.Entity("ConsoleApp1.Recursos", b =>
                {
                    b.HasOne("ConsoleApp1.Usuarios", "usuario")
                        .WithMany()
                        .HasForeignKey("usuarioId");
                });

            modelBuilder.Entity("ConsoleApp1.Tareas", b =>
                {
                    b.HasOne("ConsoleApp1.Recursos", "responsable")
                        .WithMany()
                        .HasForeignKey("responsableId");

                    b.HasOne("ConsoleApp1.TipoTarea", "tipo")
                        .WithMany()
                        .HasForeignKey("tipoId");
                });
#pragma warning restore 612, 618
        }
    }
}
